from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_PHASE = "INVALID_PHASE"
    VERSION_CONFLICT = "VERSION_CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    NOT_FOUND = "NOT_FOUND"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    INTERNAL_ERROR = "INTERNAL_ERROR"

